### ISSUE TITLE
No predict method

### ISSUE THREAD

**Issue by nikosGeography** [cran/RFpredInterval#1]
First of all thank you for creating the package. The documentation is easy to follow and implement.

The way the` pibf` method is currently set up, the only way to get predictions for new data is to input them as `test_data` while training the model. This makes it much more difficult to use in a real-life application where you want to produce new prediction intervals as new data comes in. Is there any solution for this?

More specifically, I am working with spatial data which I convert them to a data.frame in two spatial resolutions (coarse and high). Then I create a model at the coarse spatial scale and I would like to `predict` the response variable at the high spatial scale.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
